### ISSUE TITLE
Fix File Upload 

### ISSUE THREAD

**Issue by cynthiakonar** [cynthiakonar/approval-system#1]
File upload is not working in Request for Workflow dialog. Currently, the file is being picked from the device but not being stored on the backend. 

1. Achieve this functionality of storing the file in firebase and add an option to download the file once workflow is added.
2. Create a PR and attach screenshots of working site.
3. Link the PR with this issue

Below is the screen whether the file is being picked.
![image](https://github.com/cynthiakonar/approval-system/assets/89989829/c6576810-0224-41c3-a013-641ec2baf455)

**Comment by Priyammm05** [comment]
Can you please elaborate this issue ?

**Comment by cynthiakonar** [comment]
Hi, I have updated the issue details. Please check and let me know whether
you will take it up.

*Thank you.*

*Regards,*

*Cynthia Konar*

**Comment by Priyammm05** [comment]
Ok so the issue is that even though the file is being picked, its still not being stored on the backend. Right ?

So I have to work on that ?

**Comment by cynthiakonar** [comment]
Yes @Priyammm05. If you will take up this issue, please send me your email id (you can mail me) so that I may add you to the Firebase Console.

**Comment by Priyammm05** [comment]
Okk @cynthiakonar I will read and check the code today and can start from tomorrow. I will update you till evening

**Comment by Priyammm05** [comment]
I have checked it and will like to work on this. @cynthiakonar 

email: priyam05soni@gmail.com

Do this project requires any additional setup or something ?

**Comment by cynthiakonar** [comment]
> I have checked it and will like to work on this. @cynthiakonar
> 
> email: [priyam05soni@gmail.com](mailto:priyam05soni@gmail.com)
> 
> Do this project requires any additional setup or something ?

I have mailed you the additional details. Please check them and let me know.

**Comment by Priyammm05** [comment]
Hey @cynthiakonar actually I'm getting a firebase error when I'm trying to upload a file to firebase.

FirebaseError: Firebase Storage: User does not have permission to access 'files/OS_Full_Notes.pdf'. (storage/unauthorized)

**Comment by Priyammm05** [comment]
Can you ping me on my discord Priyamm#5570

**Comment by Priyammm05** [comment]
![image](https://github.com/cynthiakonar/approval-system/assets/80326453/dd8001e0-8a3b-4281-968c-9c9fab90e466)

done this and have also added the feature where user can download the file.
Supported files are [images/pdf]

**Comment by Priyammm05** [comment]
![image](https://github.com/cynthiakonar/approval-system/assets/80326453/01e29ae5-0a2a-4c42-b7b0-337b06215da3)

Updated the image at leading

**Comment by cynthiakonar** [comment]
Looks good! You can create a PR and link this issue with it @Priyammm05
